plugins {
	id 'java'
	id 'org.springframework.boot' version '3.2.1'
	id 'io.spring.dependency-management' version '1.1.4'
	id 'org.asciidoctor.jvm.convert' version '3.3.2'
	id 'com.epages.restdocs-api-spec' version '0.18.4'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	asciidoctorExt
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

ext {
	snippetsDir = file('build/generated-snippets')
}

dependencies {
	// Spring WEB
	implementation 'org.springframework.boot:spring-boot-starter-web'

	// Spring JPA
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

	// LOMBOK
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	// MYSQL
	runtimeOnly 'com.mysql:mysql-connector-j'
	testImplementation 'com.h2database:h2'

	// Spring TEST
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.awaitility:awaitility'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'

	// Spring REST Docs
	asciidoctorExt 'org.springframework.restdocs:spring-restdocs-asciidoctor'
	testImplementation 'org.springframework.restdocs:spring-restdocs-mockmvc'

	// Swagger-ui
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.2.0'

	// OpenAPI
	testImplementation 'com.epages:restdocs-api-spec-mockmvc:0.18.4'

	// JWT
	implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'

	// Redis
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'

	// WebSocket
	implementation 'org.springframework.boot:spring-boot-starter-websocket'

	//SMTP
	implementation 'org.springframework.boot:spring-boot-starter-mail'

	// coolSMS
	implementation 'net.nurigo:sdk:4.3.0'

	// S3
	implementation 'org.springframework.cloud:spring-cloud-starter-aws:2.2.6.RELEASE'
	testImplementation 'io.findify:s3mock_2.13:0.2.6'

	// AWS rekognition
	implementation platform('software.amazon.awssdk:bom:2.25.0')
	implementation 'software.amazon.awssdk:rekognition'

	// Logback
	implementation 'ch.qos.logback.contrib:logback-json-classic:0.1.5'
	implementation 'ch.qos.logback.contrib:logback-jackson:0.1.5'
	implementation 'com.fasterxml.jackson.core:jackson-databind:2.15.2'
	implementation 'net.logstash.logback:logstash-logback-encoder:7.3'

	// Firebase
	implementation 'com.google.firebase:firebase-admin:9.2.0'

	//AWS Parameter Store
	implementation platform("io.awspring.cloud:spring-cloud-aws-dependencies:3.1.0")
	implementation 'io.awspring.cloud:spring-cloud-aws-starter-parameter-store'

	// MongoDB
	implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
	testImplementation 'de.flapdoodle.embed:de.flapdoodle.embed.mongo.spring30x:4.11.0'
}

test {
	outputs.dir snippetsDir
	useJUnitPlatform()
}

asciidoctor {
	configurations 'asciidoctorExt'
	attributes 'snippets': snippetsDir
	sourceDir = file('src/docs/asciidoc')
	outputDir = file("${layout.buildDirectory.get()}/docs/asciidoc")

	doFirst {
		file(snippetsDir).mkdirs()
	}
	
	dependsOn test
	inputs.dir snippetsDir
}

tasks.register('copyDocumentToStatic', Copy) {
	dependsOn asciidoctor
	from("${layout.buildDirectory.get()}/docs/asciidoc")
	into("${layout.buildDirectory.get()}/resources/main/static/docs")
}

bootJar {
	dependsOn tasks.named('copyDocumentToStatic')
}