plugins {
	id 'java'
	id 'org.springframework.boot' version '3.2.1'
	id 'io.spring.dependency-management' version '1.1.4'
	id 'org.asciidoctor.jvm.convert' version '3.3.2'
	id 'com.epages.restdocs-api-spec' version '0.15.3'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	asciidoctorExt
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

ext {
	snippetsDir = file('build/generated-snippets')
}

dependencies {
	// Spring WEB
	implementation 'org.springframework.boot:spring-boot-starter-web'

	// Spring JPA
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

	// LOMBOK
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	// MYSQL
	runtimeOnly 'com.mysql:mysql-connector-j'
	testImplementation 'com.h2database:h2'

	// Spring TEST
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	// Spring REST Docs
	asciidoctorExt 'org.springframework.restdocs:spring-restdocs-asciidoctor'
	testImplementation 'org.springframework.restdocs:spring-restdocs-mockmvc'
	asciidoctorExt 'org.springframework.restdocs:spring-restdocs-asciidoctor'

	// restdocs-api-spec (OpenAPI 3)
	testImplementation 'com.epages:restdocs-api-spec-mockmvc:0.15.3'

	// JWT
	implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'

	// Redis
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'

	// coolSMS
	implementation 'net.nurigo:sdk:4.3.0'

	// Swagger UI
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.2.0'

	// Spring TEST
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

}

repositories {
	mavenCentral()
}

ext {
	snippetsDir = file('build/generated-snippets')
}

test {
	useJUnitPlatform()
	outputs.dir snippetsDir
}

asciidoctor {
	inputs.dir snippetsDir
	dependsOn test
}

// restdocs-api-spec OpenAPI
openapi3 {
	server = "http://localhost:8080"
	title = "라잇"
	description = "Chill application"
	version = "0.0.1"
	format = "yaml"
	outputDirectory = "build/api-spec"
}

// openapi3 Task running after asciidoctor
tasks.register('generateOpenApi') {
	dependsOn asciidoctor
	doLast {
		tasks.openapi3.execute()
	}
}

// BootJar (Swagger UI, REST Docs)
bootJar {
	dependsOn generateOpenApi
	from("${asciidoctor.outputDir}/html5") {
		into "static/docs"
	}
	from("${project.buildDir}/api-spec") {
		into "static/docs"
	}
}